# Generated by Django 5.2.7 on 2025-10-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=200)),
                ('tag', models.ManyToManyField(to='api.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
