# Generated by Django 5.2.7 on 2025-10-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_quote_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='Author',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote',
            field=models.CharField(default='Enter quote...', max_length=200),
        ),
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default='Enter author...', max_length=200),
        ),
    ]
